import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({
//   subsets: ["latin"],
//   weight: ["400", "700"],
//   variable: "--font-inter",
// });

export const metadata: Metadata = {
  title: "Bank Dash",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon-icon.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans`}>
        {children}
      </body>
    </html>
  );
}
